input-output-hk/chain-wallet-libs

- .github/workflows/release.yaml
I think this is what the command was supposed to do, it's probably fine, but if both files will always exist it may be better to just write the paths directly.
> fix invalid unix cp command in release

- .github/workflows/release.yaml
After fixing #1 it seems release was also failing on Windows, although I'm not sure why. This is not the most elegant fix, but I don't know much powershell.
> fix invalid copy command in release on windows

- wallet/src/blockchain.rs
- wallet/src/recovering/daedalus.rs
- wallet/src/recovering/icarus.rs
- wallet/src/recovering/mod.rs
- wallet/src/recovering/paperwallet.rs
add support for paper wallet. We don't yet enforce recovering from the daedalus paper wallet mnemonics as this is a wallet choice more than a technically sounds decision
relates to #4
> Recover from a Paperwallet

- .github/workflows/release.yaml
- wallet-js/Cargo.toml
Add `chain-wallet-libs-{version}-web.tgz` and `chain-wallet-libs-{version}-nodejs.tgz` to the release. These are npm packages, which can be installed with `npm install`.
This would be the 3rd item in #15 
Also change the wallet-js crate version to `0.2.0`. I'm not completely sure about this part, I guess we want all the subcrates to have the same version?
> Add release wasm job

- bindings/wallet-jni/src/lib.rs
EDIT: `with_capacity` doesn't set the `len` of the vec. And `get_byte_array_region` copies `buf.len()` elements. So even if `with_capacity` does allocate the memory, the buffer passed to the function has a length of 0. (And doesn't copy anything)
By the way, I think it should be possible to write a few tests in java (not android, just a normal jvm java binary) for this little things. Although, on the other hand, we would probably like to test this on the android tests, in which case it wouldn't really add that much. What do you think? @NicolasDP @danielSanchezQ
> fix allocation bug in jni binding

- .github/workflows/release.yaml
- bindings/wallet-cordova/BUILD.md
- bindings/wallet-cordova/build_jni.py
Add python (3) script for building the jni and copy the files from the root's target directory to the proper directory inside the plugin.
The script assumes that's been run from the directory it is in (as the paths are relative).
relates to #31
> Add wallet cordova build jni script

- bindings/wallet-cordova/.gitignore
- bindings/wallet-cordova/BUILD.md
- bindings/wallet-cordova/README.md
- bindings/wallet-cordova/TESTING.md
- bindings/wallet-cordova/build_wasm.py
- bindings/wallet-cordova/plugin.xml
- bindings/wallet-cordova/src/electron/walletProxy.js
replace the mocks in #47 for an actual implementation. This is rebased from that, so either merge #47 before this, or merge this and close the other.
- Add an electron implementation
- Move the content of `README.md` to a new `TESTING.md`, as the README is what's added to the package and is not that relevant for users.
- Add some placeholders in the README, I'm not sure if it's best to add some examples now, because I the user-facing plugin API may change a bit yet.
The electron implementation requires that node integrations are enabled in the app. This is used to load the webassembly by using node's `fs` and some electron functionality to resolve the paths. There may be some ways of work around that (by providing a preload script and requiring the user to load it, maybe), I'm not sure if …
> Add electron plugin impl

- bindings/wallet-core/Cargo.toml
- bindings/wallet-core/src/c.rs
- bindings/wallet-core/src/conversion.rs
- bindings/wallet-core/src/wallet.rs
- bindings/wallet-js/src/lib.rs
- wallet/src/transaction/dump.rs
- wallet/tests/daedalus.rs
- wallet/tests/utils/mod.rs
- wallet/tests/yoroi.rs
The transaction were not formatted to be sent to the node already, they needed the extra step to be ready send.
This PR makes sure the transactions are formatted into a ready to send fragment. Also add the tests for the transaction dump into the new address.
> Return ready-to send fragment raw

- bindings/wallet-jni/java/WalletTest.java
- bindings/wallet-jni/java/com/iohk/jormungandrwallet/Conversion.java
- bindings/wallet-jni/java/com/iohk/jormungandrwallet/Wallet.java
- bindings/wallet-jni/src/lib.rs
- Fix bug where the functions were readings pointer types from jni instead of `jlong`, breaking things in 32bits. I think this could've been avoided with some lint that checks from redundant casts, as the code was casting the pointers to the same type. I'll see if it's possible. I don't know if there is a better way.
- Add conversion get ignored to jni.
> add conversion get ignored and fix pointer bug

- bindings/wallet-cordova/src/android/WalletPlugin.java
- bindings/wallet-cordova/src/electron/walletProxy.js
- bindings/wallet-cordova/tests/tests.js
- bindings/wallet-cordova/www/wallet.js
- bindings/wallet-jni/java/WalletTest.java
- bindings/wallet-jni/java/com/iohk/jormungandrwallet/Conversion.java
- bindings/wallet-jni/java/com/iohk/jormungandrwallet/Wallet.java
- bindings/wallet-jni/src/lib.rs
- Add function to set wallet state to cordova plugin, for electron and android 
- Add function to get conversion ignored to cordova plugin, for electron and android
This is branched from #60 because without the JNI bindings this won't  work. So that should be merged first (or just close and merge this). I could also rebase this to not include those commits, if the reviewer prefers that (but still shouldn't be merged without the other).
> Add conversion get ignored and set state android electron

- bindings/wallet-cordova/src/electron/walletProxy.js
- bindings/wallet-js/src/lib.rs
- bindings/wallet-js/src/utils.rs
implements #54 
export `set_panic_hook` 
also, call the function when initializing the electron plugin.
> Expose set panic hook

- bindings/wallet-core/src/wallet.rs
- wallet/src/recovering/daedalus.rs
- wallet/src/recovering/icarus.rs
- wallet/src/recovering/mod.rs
- wallet/tests/daedalus.rs
- wallet/tests/yoroi.rs
relates to #57 
replace the `Vec` in `RecoveringDaedalus` and `RecoveringIcarus` by `HashMap` with `UtxoPointer` as key, and return an error if we try to add an utxo twice.
Not sure if this is what we want, but it's just a few lines so I implemented anyway.
Btw, it seems like there is some code duplication between the two recovering structs, although it's rather minor and it's probably not worth to deal with.
> Wallet retrieve funds only once

- bindings/wallet-cordova/tests/tests.js
Somehow at some point I changed the function name without including the change in the test file. @eugene-babichenko in case you run into this.
> change cordova plugin test to match api get ignored function name

- .github/workflows/release.yaml
Add the ios libs to the plugin's package.
Basically run the python script in a separate job in macos and pass an artifact to the packaging job.
> Add wallet cordova ios to release

- README.md
- bindings/wallet-cordova/src/electron/walletProxy.js
- bindings/wallet-cordova/www/wallet.js
- Check argument types in js (top module) for every function, so we can rely on that for every platform.
- Normalize the electron plugin so it uses the same types as the native ones.
- Fix the documentation, because pointers are actually string and not numbers. (it doesn't make any difference, because they are never constructed by the api user, they are just a handle type).
> Add cordova argscheck

- bindings/wallet-cordova/plugin.xml
- bindings/wallet-cordova/src/android/WalletPlugin.java
- bindings/wallet-cordova/tests/plugin.xml
- bindings/wallet-cordova/tests/tests.js
- bindings/wallet-cordova/www/wallet.js
- bindings/wallet-core/src/error.rs
- bindings/wallet-core/src/wallet.rs
- bindings/wallet-jni/Cargo.toml
- bindings/wallet-jni/java/WalletTest.java
- bindings/wallet-jni/java/com/iohk/jormungandrwallet/Proposal.java
- bindings/wallet-jni/java/com/iohk/jormungandrwallet/Wallet.java
- bindings/wallet-jni/src/lib.rs
- wallet/src/transaction/builder.rs
- Also add the top-level cordova plugin interface with the android implementation.
- Add an error type when in the TransactionBuilder when balance doesn't check, because a panic crashes the app in android (and it's easy to trigger if someone forgets to set the wallet state). Please review that the error report makes sense.
> Add vote cast to jni

- Cargo.toml
Set LTO=yes for whole workspace on the `release` profile.
I think this solves the release issues, although I'm not sure if it is a reasonable decision for a library.
I think the problem is that when the c-bindings crate (jormungandrwallet) with `cargo rustc -- --LTO` doesn't mean that the `wallet` crate builds with LTO, as the `rustc` command doesn't forward compilation flags to the dependencies, so the `wallet` crate doesn't have the bitcode embedded.
It may be also possible to set this with environment variables only for release?
> set LTO to true in the release profile

- bindings/wallet-js/Cargo.toml
The release pipeline is broken for cordova (the webassembly part)
Workaround taken from https://github.com/rustwasm/wasm-pack/issues/886
Maybe we should include more things in the integration checks.
> enable mutable globals in wasm-opt

- wallet/src/scheme/bip44.rs
- wallet/src/scheme/freeutxo.rs
- wallet/src/scheme/rindex.rs
- wallet/src/store/mod.rs
- wallet/src/store/utxo.rs
- wallet/src/transaction/dump.rs
- wallet/src/transaction/witness_builder.rs
This changes the UtxoStore generics arguments to be able to use `SecretKey` instead of `Key`, which is used for the free keys. As the free keys have no derivation, they are not grouped by derivation path in the utxo store, but by public key (before this, they had a fake derivation path given by the order they were recovered).
> Fix free key derivation hack

- .github/workflows/release.yaml
- bindings/wallet-js/patch-packaging.sh
add a temporal? patch for the fact that wasm-pack is not including the
'_bg.js' file in the package.json
> add wallet-js bundler target

- CHANGELOG.md
- bindings/wallet-js/src/lib.rs
- bindings/wallet-js/tests/web.rs
Add option to generate keys from seed. Which is useful for testing.
> wallet-js generate key from seed

- wallet/Cargo.toml
- wallet/src/store/utxo.rs
Use imhamt instead of im-rc
As a possible solution to #112 (at least in the short term)
The idea is to replace the im-rc (HashMap, OrdMap) with the imhamt, which (safe or not) is used everywhere already. The `OrdMap` can't really be replaced, but we can just sort a `Vec` as we are not really working with large amounts of utxos at the moment.
Later down the road we can benchmark and optimize if it is a problem, and anyway we may need to change things when (if?) we start considering persistent storage for the utxo store.
Also, remove the `RefCell` which I'm not sure what was for.
> Remove im-rc

- .github/workflows/ci_checks.yaml
- bindings/wallet-jni/java/run_test.py
there may be a cleaner solution in the long term (maybe code
generation?), but I think there is some value in having these running
automatically.
the 32bits version is useful because it's not really that hard to mess
up the stack and some android architectures have 32bits words
> run java tests in jvm in ci

- bindings/wallet-cordova/README.md
Although I'm already keeping track of things in the changelog, I think having this table somewhere is useful. This is the plugin's subdirectory readme, so it is not really that visible, but I think it's too much information for the main one.
I'll try to fill all of the checkboxes soon, but just in case.
> add cordova plugin status to plugin readme

- .github/workflows/release.yaml
- bindings/wallet-js/patch-packaging.sh
It would be cheeky to publish something named `wallet-js` into the global npm namespace.
Give it a scope that I have secured control on at npmjs.com.
> Put wallet-js package into @iohk-jormungandr scope

- .gitmodules
- Cargo.toml
- bindings/wallet-c/Cargo.toml
- bindings/wallet-core/Cargo.toml
- bindings/wallet-core/src/vote.rs
- bindings/wallet-jni/Cargo.toml
- bindings/wallet-js/Cargo.toml
- hdkeygen/Cargo.toml
- wallet/Cargo.toml
- wallet/src/blockchain.rs
This will normalize chain-libs crates in the dependency graph of projects that use both chain-wallet-libs and chain-libs directly.
Resolves #117
> Convert chain-libs submodule to git dependencies

- .github/workflows/ci_checks.yaml
- .github/workflows/release.yaml
- CHANGELOG.md
- Cargo.toml
- bindings/wallet-c/Cargo.toml
- bindings/wallet-cordova/tests/plugin.xml
- bindings/wallet-core/Cargo.toml
- bindings/wallet-jni/Cargo.toml
- bindings/wallet-js/Cargo.toml
- bindings/wallet-js/src/lib.rs
- bindings/wallet-js/tests/web.rs
- keygen/.gitignore
- keygen/Cargo.toml
- keygen/LICENSE-APACHE
- keygen/LICENSE-MIT
- keygen/patch-packaging.sh
- keygen/src/lib.rs
- keygen/src/utils.rs
- keygen/tests/web.rs
- symmetric-cipher/Cargo.toml
- wallet/Cargo.toml
closes #124
TODO:
Maybe remove the key generation from wallet-js? That stuff is already in `js-chain-libs` anyway.
Probably keygen is a bad name. (Should we call it daedalus-catalyst-interop-js?)
> Add key generation and pin encryption lib

- .github/workflows/ci_jni_build.yaml
For some reason that I don't understand, when cross compiling to arm64 for android, the library is missing a dynamic dependency to `libdl.so`. It only happens with the `release` profile, and I think only with `gcc` as a linker (because that's what `cross` uses, and I'm using clang without cross locally and it doesn't happen).
By adding `-ldl` explicitly as an extra linker flag, it's properly added to the elf header, although I still don't know if that's enough to fix the issue completely as I don't have a way to test on that architecture.
Also, I don't really know why are we downgrading `cross`, seems like a copy-paste leftover.
> Use latest cross and add libdl

- bindings/wallet-js/src/lib.rs
as it is needed for the browser platform support, even if it is not used
right now
I removed this when creating the other keygen library, which only needs the encryption, but I included both in case someone wanted to use it for testing. It was wrong to remove it from here, though.
> reintroduce decryption function in wallet-js

- bip39/Cargo.toml
- hdkeygen/Cargo.toml
- symmetric-cipher/Cargo.toml
- wallet/Cargo.toml
This update contains a fix to prevent a compilation error in the
upcoming rustc version.
> update cryptoxide to 0.3.1

- CHANGELOG.md
- bindings/wallet-cordova/src/android/WalletPlugin.java
- bindings/wallet-cordova/tests/src/main.js
- bindings/wallet-cordova/www/wallet.js
- bindings/wallet-jni/java/WalletTest.java
- bindings/wallet-jni/java/com/iohk/jormungandrwallet/Settings.java
continues with #142 
The java part probably can be rewritten more elegantly, but I don't know java that well to do it from the start. I'd like to know first if this js API looks ok, and if it poses any hardship for the objective c part before investing time in beautification.
As a side note, we could simplify this by bundling serialization in the C api, and exporting `settings_from_json` and  `settings_to_json` functions... The reason I'm not doing that is because I don't think it's a good idea for the C api, but maybe we don't actually care... We don't have users for the c api by itself, so I'm not sure.
Not that this is complicated, though, it's mostly boilerplatey because of all the settings fields, maybe it makes more sense to invest some time in code generation, though.
> Add cordova settings get new

- bindings/wallet-core/src/vote.rs
Update vote encryption to changes in API from #https://github.com/input-output-hk/chain-libs/pull/551
> Pass crs to encry_vote function

- bindings/wallet-core/src/error.rs
- bindings/wallet-core/src/wallet.rs
- wallet/src/account.rs
- wallet/src/states.rs
- wallet/tests/account.rs
- wallet/tests/free_keys.rs
- wallet/tests/utils/mod.rs
also add error when there not enough funds for creating the transaction
I realized when working on #149 that the funds tracking for the account wallet was incorrect, we were setting the available funds to the funds required for the transaction (after creating the transaction).
It's not a huge issue because we were not using the value for validation anyway, but with this PR we now throws an error if there are not enough funds for the transaction, besides fixing the logic.
> fix invalid account funds tracking

- bindings/wallet-core/src/c/vote.rs
Remove mention of ristretto backend from tests so that we can change it without rewriting tests
> remove mention of explicit backend from tests

- bindings/wallet-c/src/lib.rs
- bindings/wallet-js/src/lib.rs
- wallet/src/scheme/freeutxo.rs
Removed `PayloadType` enum from wallet-js and wallet-c, as it is no
longer used.
Reduce cloning in UTxO wallet initialization.
> Small fixes in wallet bindings API and code

- .github/workflows/ci_integration.yaml
except for the ones that are needed to be passed across jobs (which have
a 1-day retention clause).
> don't upload artifacts on integration

- hdkeygen/src/rindex/hdpayload.rs
- wallet/Cargo.toml
- wallet/src/account.rs
- wallet/src/scheme/bip44.rs
- wallet/src/scheme/freeutxo.rs
- wallet/src/scheme/rindex.rs
- wallet/src/states.rs
This replaces the linked hash map implementation used for state management with hashlink.
Because
> The wallet state data structure in chain-wallet-libs reinvents a linked hash table using raw pointers.
>
> To avoid having to deal with soundness issues ourselves, we should use a ready-made, MIRI- and world-tested ordered hash table implementation from a library like hashlink instead.
> re-implement States with hashlink

- .github/workflows/ci_checks.yaml
This should benefit from the cache for compiled crates.
> CI: Use actions-rs/install to install cbindgen

- wallet/src/states.rs
I removed the key field from the `StateRef` struct, but forgot to remove this test constructor in #166
> remove unused argument in tests

- Cargo.lock
- bindings/wallet-c/Cargo.toml
- bindings/wallet-cordova/package.json
- bindings/wallet-cordova/tests/plugin.xml
- bindings/wallet-core/Cargo.toml
- bindings/wallet-jni/Cargo.toml
- bindings/wallet-js/Cargo.toml
This is port of the commits https://github.com/input-output-hk/chain-wallet-libs/commit/09b38e6689271094c99657037dc4c3ea92d79e88 and https://github.com/input-output-hk/chain-wallet-libs/commit/ad4ddaacd191959be8594e59d4d7f58ce4d41fde from the https://github.com/input-output-hk/chain-wallet-libs/commits/catalyst-fund6 branch
> 0.7.0-pre4: update manifest version numbers

- bindings/wallet-cordova/src/android/WalletPlugin.java
The builtin code in the android sdk 30 for extracting longs from a
JSONArray parses big (in absolute value) `Long` values incorrectly,
because first it parses them as `Double`, which loses precision.
In particular, when combined with the _tagged pointers_ feature in
android 11 this creates invalid pointers, as we are passing them as
handles to js and parsing them back (but now they get rounded).
In the future, we may stop using pointers as handles when we migrate to
uniffi, but we can't rely on the Long parse function anyway, so this
replaces every call, even if the values are not pointers and the actual
values can't get big enough in practice, to keep things consistent and
as a reminder (in case we copy-paste some code, for example).
> cordova: replace toLong calls

- Cargo.lock
- Cargo.toml
- bip39/Cargo.toml
- bip39/src/entropy.rs
- bip39/src/mnemonic.rs
- bip39/src/seed.rs
- hdkeygen/Cargo.toml
- hdkeygen/src/account.rs
- hdkeygen/src/rindex/hdpayload.rs
- symmetric-cipher/Cargo.toml
- symmetric-cipher/src/lib.rs
- wallet/Cargo.toml
- wallet/src/password.rs
- wallet/src/recovering/mod.rs
I think we can switch to crates.io as soon as we have a release that
compiles for all our targets, in the meantime, this should enable us to
continue doing releases.
Since cryptoxide doesn't expose `secure_memset` anymore, this replaces
it with `zeroize`. Whether this is needed or not, I'm not sure, since
`secure_memset` was just a `for` loop anyway, we could just replace it
with a loop too, but I don't see any problems with `zeroize`.
> update cryptoxide to latest master

- Cargo.toml
This seems to reduce the size of the shared android library by half (2.5M to 1.2M), which is not a lot, but may be nice for the mobile targets at least. 
Just as a note, while android strips native libraries by default, it does not seem to be able to do it with this lib (it shows a warning when building).
All of this probably applies for ios too, but I haven't measured that.
> strip symbols in release profile
