hdkeygen/src/account.rs
wallet-c/src/lib.rs
wallet-js/src/lib.rs
wallet/src/blockchain.rs
wallet/src/lib.rs
wallet/src/recovering/mod.rs
wallet/src/transaction/builder.rs
wallet/src/transaction/dump.rs
wallet/src/transaction/input_selection.rs
wallet/src/transaction/mod.rs
wallet/src/transaction/witness_builder.rs

Transaction builder

---

.github/workflows/release.yaml

Fix remaining CI errors in paths for release.
[Test release](https://github.com/danielSanchezQ/chain-wallet-libs/releases/tag/v0.testrelease5)

Release ci fix

---

bindings/wallet-core/src/wallet.rs
wallet/Cargo.toml
wallet/src/blockchain.rs

Expose settings data

---

wallet/src/transaction/dump.rs

Move inputs to ignored if mk_output fails for build_tx_and_clear

---

bindings/wallet-android/src/main/java/com/iohk/jormungandrwallet/Wallet.kt
bindings/wallet-c/src/lib.rs
bindings/wallet-c/wallet.h
bindings/wallet-cordova/src/android/WalletPlugin.java
bindings/wallet-cordova/src/android/jormungandrwallet/Wallet.java
bindings/wallet-cordova/src/electron/walletProxy.js
bindings/wallet-cordova/tests/tests.js
bindings/wallet-cordova/www/wallet.js
bindings/wallet-core/src/c.rs
bindings/wallet-core/src/wallet.rs
bindings/wallet-jni/java/com/iohk/jormungandrwallet/Wallet.java
bindings/wallet-jni/src/lib.rs
bindings/wallet-js/src/lib.rs
hdkeygen/src/account.rs
wallet/src/lib.rs

expose Account ID

---

bindings/wallet-core/src/lib.rs
bindings/wallet-js/src/lib.rs

Add vote cast to wallet js

---

bindings/wallet-cordova/src/electron/walletProxy.js
bindings/wallet-cordova/tests/tests.js

Add vote to cordova electron

---

bindings/wallet-cordova/plugin.xml
bindings/wallet-cordova/src/android/WalletPlugin.java
bindings/wallet-cordova/tests/tests.js
bindings/wallet-cordova/www/wallet.js
bindings/wallet-core/src/c.rs
bindings/wallet-core/src/wallet.rs
bindings/wallet-jni/java/WalletTest.java
bindings/wallet-jni/java/com/iohk/jormungandrwallet/PendingTransactions.java
bindings/wallet-jni/java/com/iohk/jormungandrwallet/Wallet.java
bindings/wallet-jni/src/lib.rs
wallet/src/lib.rs
wallet/src/recovering/daedalus.rs
wallet/src/recovering/icarus.rs
wallet/src/transaction/dump.rs
wallet/tests/daedalus.rs
wallet/tests/yoroi.rs

This add the core functionalities to update the wallet state once a transaction has been configmed

add mean to update the wallet state when a transaction is confirmed

---

.github/workflows/release.yaml
bindings/wallet-android/src/main/jniLibs/rename_targets.py
bindings/wallet-cordova/build_jni.py
bindings/wallet-cordova/plugin.xml

Fix wrong android ABI name.
As per: https://developer.android.com/ndk/guides/abis

change amd64-v8a to arm64-v8a

---

bindings/wallet-core/src/c.rs
bindings/wallet-core/src/error.rs
bindings/wallet-jni/java/WalletTest.java
symmetric-cipher/src/lib.rs

I forgot to check `ChaCha20Poly1305::decrypt` return value. With this, using a wrong password would return an error.

add decryption authentication check

---

bindings/wallet-c/check_header.sh

also, make it use posix shell instead of bash

remove line with version before diffing

---

CHANGELOG.md
bindings/wallet-js/src/lib.rs
bindings/wallet-js/tests/web.rs

Add sign/verify functions to wallet-js. Also add the other kind of private keys.

wallet-js add signing/verification

---

.github/workflows/release.yaml

I edited the wrong file in #128 
We probably should try to 'refactor' that

need link argument in release workflow too

---

.github/workflows/release.yaml

Use official upload release asset

---

.github/workflows/ci_checks.yaml

This fixes the other CI error in #131 and #130

run apt update before apt install

---

bindings/wallet-cordova/plugin.xml

I forgot to update this the last time.
Maybe we should put together a bump versions script.

fix cordova plugin.xml version

---

bindings/wallet-cordova/www/wallet.js

not really important, but it's better to remove this. It probably wasn't worth to keep it in the first place, but it was just in case we needed to make a quick fix without breaking anything else.

remove deprecated proposalNew

---

bindings/wallet-core/src/c/vote.rs
bindings/wallet-core/src/vote.rs
hdkeygen/src/account.rs
hdkeygen/src/rindex/hdpayload.rs
symmetric-cipher/src/lib.rs
wallet/src/store/utxo.rs

closes #148
also apply some automated clippy fixes.
and also fix the compilation issues because of the changes in `chain-libs`

Fix to payload and clippy issues

---

CHANGELOG.md
bindings/wallet-c/src/lib.rs
bindings/wallet-c/wallet.h
bindings/wallet-cordova/src/android/WalletPlugin.java
bindings/wallet-cordova/src/ios/WalletPlugin.h
bindings/wallet-cordova/src/ios/WalletPlugin.m
bindings/wallet-cordova/tests/src/main.js
bindings/wallet-cordova/www/wallet.js
bindings/wallet-core/src/c/mod.rs
bindings/wallet-core/src/c/vote.rs
bindings/wallet-core/src/vote.rs
bindings/wallet-core/src/wallet.rs
bindings/wallet-jni/java/WalletTest.java
bindings/wallet-jni/java/com/iohk/jormungandrwallet/JormungandrWalletException.java
bindings/wallet-jni/java/com/iohk/jormungandrwallet/Wallet.java
bindings/wallet-jni/src/lib.rs
hdkeygen/src/account.rs
hdkeygen/src/rindex/hdpayload.rs
symmetric-cipher/src/lib.rs
wallet/src/account.rs
wallet/src/store/utxo.rs

add spending counter getter.
~~for now only for android~~ iOS too, although untested
also, this is (now) rebased on #150, ~~please review that one first~~ merged already

add spending counter getter to cordova

---

bindings/wallet-cordova/src/ios/WalletPlugin.h
bindings/wallet-cordova/src/ios/WalletPlugin.m

it was somehow removed while merging other stuff

[restore] implementation of on-chain settings in iOS plugin

---

.github/workflows/python-scripts.yml
bindings/wallet-android/src/main/jniLibs/rename_targets.py
bindings/wallet-cordova/build_ios.py
bindings/wallet-cordova/build_jni.py
bindings/wallet-cordova/build_wasm.py
bindings/wallet-cordova/copy_jni_definitions.py
bindings/wallet-jni/java/run_test.py

Lint Python scripts the same way we do in Jormungandr.

ci: check python scripts with black

---

.github/workflows/release.yaml
bindings/wallet-js/patch-packaging.sh
keygen/patch-packaging.sh

No longer needed with wasm-pack 0.10.

Remove the packaging patch

---

wallet/src/blockchain.rs

changed in https://github.com/input-output-hk/chain-libs/pull/613

remove mut from ledger.settings

---

bindings/wallet-cordova/src/ios/WalletPlugin.h
bindings/wallet-cordova/src/ios/WalletPlugin.m

~wip: untested~
~also lacking the setting changes for this to work properly.~

add ios block_date constructors

---

bindings/wallet-cordova/src/ios/WalletPlugin.m

cordova: fix ios ttl compilation errors

---

CHANGELOG.md

forgot to do this in a previous PR.

add ttl changes to CHANGELOG.md

---

bindings/wallet-cordova/BUILD.md
bindings/wallet-cordova/README.md
bindings/wallet-cordova/src/electron/bindings.js
bindings/wallet-core/src/wallet.rs
bindings/wallet-js/README.md
bindings/wallet-js/src/lib.rs
bindings/wallet-js/src/utils.rs
doc/getting_started.md
jsdoc.json

Added and improved method docs.
Documented some of the types defined in wallet-js API.
Also updated the docs in wallet-core to match.

JavaScript API documentation improvements and more

---

.github/workflows/ci_checks.yaml
hdkeygen/src/rindex/hdpayload.rs
wallet/tests/utils/mod.rs

Basically the same thing I did here:
https://github.com/input-output-hk/jormungandr/pull/3323

run clippy on all targets

---

Cargo.lock
hdkeygen/src/key.rs

I think this is a bit simpler than #205 and I believe achieves the same thing.

update chain-libs to b2128c8

---

wallet/src/store/utxo.rs

lints: use flat_map instead of map.flatten

---

.github/workflows/ci_integration.yaml

allow long paths on windows

---

Cargo.lock
bindings/wallet-core/src/c/settings.rs
wallet/src/blockchain.rs
wallet/tests/utils/mod.rs

Updates to the latest chain-libs version, especially with this new update https://github.com/input-output-hk/chain-libs/pull/830

Update chain-libs library 
